# Generated by Django 3.2.7 on 2021-09-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210919_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_closed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
