# Generated by Django 3.2.7 on 2021-09-19 15:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210919_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_access_closed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_closed',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, max_length=128, verbose_name='тэги')),
                ('about_me', models.TextField(blank=True, max_length=512, verbose_name='о себе')),
                ('gender', models.CharField(blank=True, choices=[('M', 'М'), ('W', 'Ж')], default='M', max_length=128, verbose_name='пол')),
                ('langs', models.CharField(blank=True, default='EN', max_length=128, verbose_name='Язык')),
                ('age_form', models.DateField(blank=True, default=datetime.date(2000, 1, 1), verbose_name='возраст')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
