# Generated by Django 3.2.7 on 2021-09-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210919_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age_form',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='langs',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'М'), ('W', 'Ж')], max_length=128, verbose_name='пол'),
        ),
    ]
