# Generated by Django 3.2.7 on 2021-09-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210920_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='langs',
            field=models.CharField(blank=True, default='EN', max_length=128, verbose_name='Язык'),
        ),
    ]
