# Generated by Django 3.2.7 on 2021-10-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210830_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='productscategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
